let array = [
  {
    id: "566",
    name: "Nigeria",
    capital: ["Abuja"],
    flag: "https://flagcdn.com/ng.svg",
    landlocked: false,
  },
  {
    id: "208",
    name: "Denmark",
    capital: ["Copenhagen"],
    flag: "https://flagcdn.com/dk.svg",
    landlocked: false,
  },
  {
    id: "074",
    name: "Bouvet Island",
    capital: "__vue_devtool_undefined__",
    flag: "https://flagcdn.com/bv.svg",
    landlocked: false,
  },
  {
    id: "642",
    name: "Romania",
    capital: ["Bucharest"],
    flag: "https://flagcdn.com/ro.svg",
    landlocked: false,
  },
  {
    id: "520",
    name: "Nauru",
    capital: ["Yaren"],
    flag: "https://flagcdn.com/nr.svg",
    landlocked: false,
  },
  {
    id: "324",
    name: "Guinea",
    capital: ["Conakry"],
    flag: "https://flagcdn.com/gn.svg",
    landlocked: false,
  },
  {
    id: "270",
    name: "Gambia",
    capital: ["Banjul"],
    flag: "https://flagcdn.com/gm.svg",
    landlocked: false,
  },
  {
    id: "796",
    name: "Turks and Caicos Islands",
    capital: ["Cockburn Town"],
    flag: "https://flagcdn.com/tc.svg",
    landlocked: false,
  },
  {
    id: "688",
    name: "Serbia",
    capital: ["Belgrade"],
    flag: "https://flagcdn.com/rs.svg",
    landlocked: true,
  },
  {
    id: "534",
    name: "Sint Maarten",
    capital: ["Philipsburg"],
    flag: "https://flagcdn.com/sx.svg",
    landlocked: false,
  },
  {
    id: "670",
    name: "Saint Vincent and the Grenadines",
    capital: ["Kingstown"],
    flag: "https://flagcdn.com/vc.svg",
    landlocked: false,
  },
  {
    id: "462",
    name: "Maldives",
    capital: ["Malé"],
    flag: "https://flagcdn.com/mv.svg",
    landlocked: false,
  },
  {
    id: "858",
    name: "Uruguay",
    capital: ["Montevideo"],
    flag: "https://flagcdn.com/uy.svg",
    landlocked: false,
  },
  {
    id: "352",
    name: "Iceland",
    capital: ["Reykjavik"],
    flag: "https://flagcdn.com/is.svg",
    landlocked: false,
  },
  {
    id: "804",
    name: "Ukraine",
    capital: ["Kyiv"],
    flag: "https://flagcdn.com/ua.svg",
    landlocked: false,
  },
  {
    id: "064",
    name: "Bhutan",
    capital: ["Thimphu"],
    flag: "https://flagcdn.com/bt.svg",
    landlocked: true,
  },
  {
    id: "484",
    name: "Mexico",
    capital: ["Mexico City"],
    flag: "https://flagcdn.com/mx.svg",
    landlocked: false,
  },
  {
    id: "862",
    name: "Venezuela",
    capital: ["Caracas"],
    flag: "https://flagcdn.com/ve.svg",
    landlocked: false,
  },
  {
    id: "162",
    name: "Christmas Island",
    capital: ["Flying Fish Cove"],
    flag: "https://flagcdn.com/cx.svg",
    landlocked: false,
  },
  {
    id: "860",
    name: "Uzbekistan",
    capital: ["Tashkent"],
    flag: "https://flagcdn.com/uz.svg",
    landlocked: true,
  },
  {
    id: "768",
    name: "Togo",
    capital: ["Lomé"],
    flag: "https://flagcdn.com/tg.svg",
    landlocked: false,
  },
  {
    id: "454",
    name: "Malawi",
    capital: ["Lilongwe"],
    flag: "https://flagcdn.com/mw.svg",
    landlocked: true,
  },
  {
    id: "834",
    name: "Tanzania",
    capital: ["Dodoma"],
    flag: "https://flagcdn.com/tz.svg",
    landlocked: false,
  },
  {
    id: "112",
    name: "Belarus",
    capital: ["Minsk"],
    flag: "https://flagcdn.com/by.svg",
    landlocked: true,
  },
  {
    id: "533",
    name: "Aruba",
    capital: ["Oranjestad"],
    flag: "https://flagcdn.com/aw.svg",
    landlocked: false,
  },
  {
    id: "368",
    name: "Iraq",
    capital: ["Baghdad"],
    flag: "https://flagcdn.com/iq.svg",
    landlocked: false,
  },
  {
    id: "260",
    name: "French Southern and Antarctic Lands",
    capital: ["Port-aux-Français"],
    flag: "https://flagcdn.com/tf.svg",
    landlocked: false,
  },
  {
    id: "776",
    name: "Tonga",
    capital: ["Nuku'alofa"],
    flag: "https://flagcdn.com/to.svg",
    landlocked: false,
  },
  {
    id: "191",
    name: "Croatia",
    capital: ["Zagreb"],
    flag: "https://flagcdn.com/hr.svg",
    landlocked: false,
  },
  {
    id: "239",
    name: "South Georgia",
    capital: ["King Edward Point"],
    flag: "https://flagcdn.com/gs.svg",
    landlocked: false,
  },
  {
    id: "887",
    name: "Yemen",
    capital: ["Sana'a"],
    flag: "https://flagcdn.com/ye.svg",
    landlocked: false,
  },
  {
    id: "458",
    name: "Malaysia",
    capital: ["Kuala Lumpur"],
    flag: "https://flagcdn.com/my.svg",
    landlocked: false,
  },
  {
    id: "652",
    name: "Saint Barthélemy",
    capital: ["Gustavia"],
    flag: "https://flagcdn.com/bl.svg",
    landlocked: false,
  },
  {
    id: "184",
    name: "Cook Islands",
    capital: ["Avarua"],
    flag: "https://flagcdn.com/ck.svg",
    landlocked: false,
  },
  {
    id: "832",
    name: "Jersey",
    capital: ["Saint Helier"],
    flag: "https://flagcdn.com/je.svg",
    landlocked: false,
  },
  {
    id: "496",
    name: "Mongolia",
    capital: ["Ulan Bator"],
    flag: "https://flagcdn.com/mn.svg",
    landlocked: true,
  },
  {
    id: "492",
    name: "Monaco",
    capital: ["Monaco"],
    flag: "https://flagcdn.com/mc.svg",
    landlocked: false,
  },
  {
    id: "036",
    name: "Australia",
    capital: ["Canberra"],
    flag: "https://flagcdn.com/au.svg",
    landlocked: false,
  },
  {
    id: "218",
    name: "Ecuador",
    capital: ["Quito"],
    flag: "https://flagcdn.com/ec.svg",
    landlocked: false,
  },
  {
    id: "246",
    name: "Finland",
    capital: ["Helsinki"],
    flag: "https://flagcdn.com/fi.svg",
    landlocked: false,
  },
  {
    id: "450",
    name: "Madagascar",
    capital: ["Antananarivo"],
    flag: "https://flagcdn.com/mg.svg",
    landlocked: false,
  },
  {
    id: "372",
    name: "Ireland",
    capital: ["Dublin"],
    flag: "https://flagcdn.com/ie.svg",
    landlocked: false,
  },
  {
    id: "752",
    name: "Sweden",
    capital: ["Stockholm"],
    flag: "https://flagcdn.com/se.svg",
    landlocked: false,
  },
  {
    id: "554",
    name: "New Zealand",
    capital: ["Wellington"],
    flag: "https://flagcdn.com/nz.svg",
    landlocked: false,
  },
  {
    id: "876",
    name: "Wallis and Futuna",
    capital: ["Mata-Utu"],
    flag: "https://flagcdn.com/wf.svg",
    landlocked: false,
  },
  {
    id: "512",
    name: "Oman",
    capital: ["Muscat"],
    flag: "https://flagcdn.com/om.svg",
    landlocked: false,
  },
  {
    id: "028",
    name: "Antigua and Barbuda",
    capital: ["Saint John's"],
    flag: "https://flagcdn.com/ag.svg",
    landlocked: false,
  },
  {
    id: "659",
    name: "Saint Kitts and Nevis",
    capital: ["Basseterre"],
    flag: "https://flagcdn.com/kn.svg",
    landlocked: false,
  },
  {
    id: "540",
    name: "New Caledonia",
    capital: ["Nouméa"],
    flag: "https://flagcdn.com/nc.svg",
    landlocked: false,
  },
  {
    id: "882",
    name: "Samoa",
    capital: ["Apia"],
    flag: "https://flagcdn.com/ws.svg",
    landlocked: false,
  },
  {
    id: "124",
    name: "Canada",
    capital: ["Ottawa"],
    flag: "https://flagcdn.com/ca.svg",
    landlocked: false,
  },
  {
    id: "702",
    name: "Singapore",
    capital: ["Singapore"],
    flag: "https://flagcdn.com/sg.svg",
    landlocked: false,
  },
  {
    id: "320",
    name: "Guatemala",
    capital: ["Guatemala City"],
    flag: "https://flagcdn.com/gt.svg",
    landlocked: false,
  },
  {
    id: "792",
    name: "Turkey",
    capital: ["Ankara"],
    flag: "https://flagcdn.com/tr.svg",
    landlocked: false,
  },
  {
    id: "524",
    name: "Nepal",
    capital: ["Kathmandu"],
    flag: "https://flagcdn.com/np.svg",
    landlocked: true,
  },
  {
    id: "438",
    name: "Liechtenstein",
    capital: ["Vaduz"],
    flag: "https://flagcdn.com/li.svg",
    landlocked: true,
  },
  {
    id: "070",
    name: "Bosnia and Herzegovina",
    capital: ["Sarajevo"],
    flag: "https://flagcdn.com/ba.svg",
    landlocked: false,
  },
  {
    id: "148",
    name: "Chad",
    capital: ["N'Djamena"],
    flag: "https://flagcdn.com/td.svg",
    landlocked: true,
  },
  {
    id: "068",
    name: "Bolivia",
    capital: ["Sucre"],
    flag: "https://flagcdn.com/bo.svg",
    landlocked: true,
  },
  {
    id: "332",
    name: "Haiti",
    capital: ["Port-au-Prince"],
    flag: "https://flagcdn.com/ht.svg",
    landlocked: false,
  },
  {
    id: "234",
    name: "Faroe Islands",
    capital: ["Tórshavn"],
    flag: "https://flagcdn.com/fo.svg",
    landlocked: false,
  },
  {
    id: "480",
    name: "Mauritius",
    capital: ["Port Louis"],
    flag: "https://flagcdn.com/mu.svg",
    landlocked: false,
  },
  {
    id: "850",
    name: "United States Virgin Islands",
    capital: ["Charlotte Amalie"],
    flag: "https://flagcdn.com/vi.svg",
    landlocked: false,
  },
  {
    id: "500",
    name: "Montserrat",
    capital: ["Plymouth"],
    flag: "https://flagcdn.com/ms.svg",
    landlocked: false,
  },
  {
    id: "328",
    name: "Guyana",
    capital: ["Georgetown"],
    flag: "https://flagcdn.com/gy.svg",
    landlocked: false,
  },
  {
    id: "580",
    name: "Northern Mariana Islands",
    capital: ["Saipan"],
    flag: "https://flagcdn.com/mp.svg",
    landlocked: false,
  },
  {
    id: "662",
    name: "Saint Lucia",
    capital: ["Castries"],
    flag: "https://flagcdn.com/lc.svg",
    landlocked: false,
  },
  {
    id: "360",
    name: "Indonesia",
    capital: ["Jakarta"],
    flag: "https://flagcdn.com/id.svg",
    landlocked: false,
  },
  {
    id: "040",
    name: "Austria",
    capital: ["Vienna"],
    flag: "https://flagcdn.com/at.svg",
    landlocked: true,
  },
  {
    id: "312",
    name: "Guadeloupe",
    capital: ["Basse-Terre"],
    flag: "https://flagcdn.com/gp.svg",
    landlocked: false,
  },
  {
    id: "232",
    name: "Eritrea",
    capital: ["Asmara"],
    flag: "https://flagcdn.com/er.svg",
    landlocked: false,
  },
  {
    id: "408",
    name: "North Korea",
    capital: ["Pyongyang"],
    flag: "https://flagcdn.com/kp.svg",
    landlocked: false,
  },
  {
    id: "690",
    name: "Seychelles",
    capital: ["Victoria"],
    flag: "https://flagcdn.com/sc.svg",
    landlocked: false,
  },
  {
    id: "050",
    name: "Bangladesh",
    capital: ["Dhaka"],
    flag: "https://flagcdn.com/bd.svg",
    landlocked: false,
  },
  {
    id: "072",
    name: "Botswana",
    capital: ["Gaborone"],
    flag: "https://flagcdn.com/bw.svg",
    landlocked: true,
  },
  {
    id: "666",
    name: "Saint Pierre and Miquelon",
    capital: ["Saint-Pierre"],
    flag: "https://flagcdn.com/pm.svg",
    landlocked: false,
  },
  {
    id: "586",
    name: "Pakistan",
    capital: ["Islamabad"],
    flag: "https://flagcdn.com/pk.svg",
    landlocked: false,
  },
  {
    id: "052",
    name: "Barbados",
    capital: ["Bridgetown"],
    flag: "https://flagcdn.com/bb.svg",
    landlocked: false,
  },
  {
    id: "474",
    name: "Martinique",
    capital: ["Fort-de-France"],
    flag: "https://flagcdn.com/mq.svg",
    landlocked: false,
  },
  {
    id: "570",
    name: "Niue",
    capital: ["Alofi"],
    flag: "https://flagcdn.com/nu.svg",
    landlocked: false,
  },
  {
    id: "585",
    name: "Palau",
    capital: ["Ngerulmud"],
    flag: "https://flagcdn.com/pw.svg",
    landlocked: false,
  },
  {
    id: "051",
    name: "Armenia",
    capital: ["Yerevan"],
    flag: "https://flagcdn.com/am.svg",
    landlocked: true,
  },
  {
    id: "104",
    name: "Myanmar",
    capital: ["Naypyidaw"],
    flag: "https://flagcdn.com/mm.svg",
    landlocked: false,
  },
  {
    id: "638",
    name: "Réunion",
    capital: ["Saint-Denis"],
    flag: "https://flagcdn.com/re.svg",
    landlocked: false,
  },
  {
    id: "528",
    name: "Netherlands",
    capital: ["Amsterdam"],
    flag: "https://flagcdn.com/nl.svg",
    landlocked: false,
  },
  {
    id: "248",
    name: "Åland Islands",
    capital: ["Mariehamn"],
    flag: "https://flagcdn.com/ax.svg",
    landlocked: false,
  },
  {
    id: "120",
    name: "Cameroon",
    capital: ["Yaoundé"],
    flag: "https://flagcdn.com/cm.svg",
    landlocked: false,
  },
  {
    id: "620",
    name: "Portugal",
    capital: ["Lisbon"],
    flag: "https://flagcdn.com/pt.svg",
    landlocked: false,
  },
  {
    id: "600",
    name: "Paraguay",
    capital: ["Asunción"],
    flag: "https://flagcdn.com/py.svg",
    landlocked: true,
  },
  {
    id: "531",
    name: "Curaçao",
    capital: ["Willemstad"],
    flag: "https://flagcdn.com/cw.svg",
    landlocked: false,
  },
  {
    id: "340",
    name: "Honduras",
    capital: ["Tegucigalpa"],
    flag: "https://flagcdn.com/hn.svg",
    landlocked: false,
  },
  {
    id: "716",
    name: "Zimbabwe",
    capital: ["Harare"],
    flag: "https://flagcdn.com/zw.svg",
    landlocked: true,
  },
  {
    id: "470",
    name: "Malta",
    capital: ["Valletta"],
    flag: "https://flagcdn.com/mt.svg",
    landlocked: false,
  },
  {
    id: "831",
    name: "Guernsey",
    capital: ["St. Peter Port"],
    flag: "https://flagcdn.com/gg.svg",
    landlocked: false,
  },
  {
    id: "392",
    name: "Japan",
    capital: ["Tokyo"],
    flag: "https://flagcdn.com/jp.svg",
    landlocked: false,
  },
  {
    id: "706",
    name: "Somalia",
    capital: ["Mogadishu"],
    flag: "https://flagcdn.com/so.svg",
    landlocked: false,
  },
  {
    id: "300",
    name: "Greece",
    capital: ["Athens"],
    flag: "https://flagcdn.com/gr.svg",
    landlocked: false,
  },
  {
    id: "116",
    name: "Cambodia",
    capital: ["Phnom Penh"],
    flag: "https://flagcdn.com/kh.svg",
    landlocked: false,
  },
  {
    id: "212",
    name: "Dominica",
    capital: ["Roseau"],
    flag: "https://flagcdn.com/dm.svg",
    landlocked: false,
  },
  {
    id: "772",
    name: "Tokelau",
    capital: ["Fakaofo"],
    flag: "https://flagcdn.com/tk.svg",
    landlocked: false,
  },
  {
    id: "316",
    name: "Guam",
    capital: ["Hagåtña"],
    flag: "https://flagcdn.com/gu.svg",
    landlocked: false,
  },
  {
    id: "288",
    name: "Ghana",
    capital: ["Accra"],
    flag: "https://flagcdn.com/gh.svg",
    landlocked: false,
  },
  {
    id: "634",
    name: "Qatar",
    capital: ["Doha"],
    flag: "https://flagcdn.com/qa.svg",
    landlocked: false,
  },
  {
    id: "222",
    name: "El Salvador",
    capital: ["San Salvador"],
    flag: "https://flagcdn.com/sv.svg",
    landlocked: false,
  },
  {
    id: "060",
    name: "Bermuda",
    capital: ["Hamilton"],
    flag: "https://flagcdn.com/bm.svg",
    landlocked: false,
  },
  {
    id: "344",
    name: "Hong Kong",
    capital: ["City of Victoria"],
    flag: "https://flagcdn.com/hk.svg",
    landlocked: false,
  },
  {
    id: "630",
    name: "Puerto Rico",
    capital: ["San Juan"],
    flag: "https://flagcdn.com/pr.svg",
    landlocked: false,
  },
  {
    id: "090",
    name: "Solomon Islands",
    capital: ["Honiara"],
    flag: "https://flagcdn.com/sb.svg",
    landlocked: false,
  },
  {
    id: "092",
    name: "British Virgin Islands",
    capital: ["Road Town"],
    flag: "https://flagcdn.com/vg.svg",
    landlocked: false,
  },
  {
    id: "178",
    name: "Republic of the Congo",
    capital: ["Brazzaville"],
    flag: "https://flagcdn.com/cg.svg",
    landlocked: false,
  },
  {
    id: "578",
    name: "Norway",
    capital: ["Oslo"],
    flag: "https://flagcdn.com/no.svg",
    landlocked: false,
  },
  {
    id: "428",
    name: "Latvia",
    capital: ["Riga"],
    flag: "https://flagcdn.com/lv.svg",
    landlocked: false,
  },
  {
    id: "604",
    name: "Peru",
    capital: ["Lima"],
    flag: "https://flagcdn.com/pe.svg",
    landlocked: false,
  },
  {
    id: "795",
    name: "Turkmenistan",
    capital: ["Ashgabat"],
    flag: "https://flagcdn.com/tm.svg",
    landlocked: true,
  },
  {
    id: "440",
    name: "Lithuania",
    capital: ["Vilnius"],
    flag: "https://flagcdn.com/lt.svg",
    landlocked: false,
  },
  {
    id: "231",
    name: "Ethiopia",
    capital: ["Addis Ababa"],
    flag: "https://flagcdn.com/et.svg",
    landlocked: true,
  },
  {
    id: "498",
    name: "Moldova",
    capital: ["Chișinău"],
    flag: "https://flagcdn.com/md.svg",
    landlocked: true,
  },
  {
    id: "674",
    name: "San Marino",
    capital: ["City of San Marino"],
    flag: "https://flagcdn.com/sm.svg",
    landlocked: true,
  },
  {
    id: "626",
    name: "Timor-Leste",
    capital: ["Dili"],
    flag: "https://flagcdn.com/tl.svg",
    landlocked: false,
  },
  {
    id: "254",
    name: "French Guiana",
    capital: ["Cayenne"],
    flag: "https://flagcdn.com/gf.svg",
    landlocked: false,
  },
  {
    id: "434",
    name: "Libya",
    capital: ["Tripoli"],
    flag: "https://flagcdn.com/ly.svg",
    landlocked: false,
  },
  {
    id: "422",
    name: "Lebanon",
    capital: ["Beirut"],
    flag: "https://flagcdn.com/lb.svg",
    landlocked: false,
  },
  {
    id: "398",
    name: "Kazakhstan",
    capital: ["Nur-Sultan"],
    flag: "https://flagcdn.com/kz.svg",
    landlocked: true,
  },
  {
    id: "292",
    name: "Gibraltar",
    capital: ["Gibraltar"],
    flag: "https://flagcdn.com/gi.svg",
    landlocked: false,
  },
  {
    id: "__vue_devtool_undefined__",
    name: "Kosovo",
    capital: ["Pristina"],
    flag: "https://flagcdn.com/xk.svg",
    landlocked: true,
  },
  {
    id: "826",
    name: "United Kingdom",
    capital: ["London"],
    flag: "https://flagcdn.com/gb.svg",
    landlocked: false,
  },
  {
    id: "798",
    name: "Tuvalu",
    capital: ["Funafuti"],
    flag: "https://flagcdn.com/tv.svg",
    landlocked: false,
  },
  {
    id: "574",
    name: "Norfolk Island",
    capital: ["Kingston"],
    flag: "https://flagcdn.com/nf.svg",
    landlocked: false,
  },
  {
    id: "417",
    name: "Kyrgyzstan",
    capital: ["Bishkek"],
    flag: "https://flagcdn.com/kg.svg",
    landlocked: true,
  },
  {
    id: "348",
    name: "Hungary",
    capital: ["Budapest"],
    flag: "https://flagcdn.com/hu.svg",
    landlocked: true,
  },
  {
    id: "238",
    name: "Falkland Islands",
    capital: ["Stanley"],
    flag: "https://flagcdn.com/fk.svg",
    landlocked: false,
  },
  {
    id: "250",
    name: "France",
    capital: ["Paris"],
    flag: "https://flagcdn.com/fr.svg",
    landlocked: false,
  },
  {
    id: "144",
    name: "Sri Lanka",
    capital: ["Sri Jayawardenepura Kotte"],
    flag: "https://flagcdn.com/lk.svg",
    landlocked: false,
  },
  {
    id: "175",
    name: "Mayotte",
    capital: ["Mamoudzou"],
    flag: "https://flagcdn.com/yt.svg",
    landlocked: false,
  },
  {
    id: "818",
    name: "Egypt",
    capital: ["Cairo"],
    flag: "https://flagcdn.com/eg.svg",
    landlocked: false,
  },
  {
    id: "807",
    name: "North Macedonia",
    capital: ["Skopje"],
    flag: "https://flagcdn.com/mk.svg",
    landlocked: true,
  },
  {
    id: "764",
    name: "Thailand",
    capital: ["Bangkok"],
    flag: "https://flagcdn.com/th.svg",
    landlocked: false,
  },
  {
    id: "426",
    name: "Lesotho",
    capital: ["Maseru"],
    flag: "https://flagcdn.com/ls.svg",
    landlocked: true,
  },
  {
    id: "694",
    name: "Sierra Leone",
    capital: ["Freetown"],
    flag: "https://flagcdn.com/sl.svg",
    landlocked: false,
  },
  {
    id: "430",
    name: "Liberia",
    capital: ["Monrovia"],
    flag: "https://flagcdn.com/lr.svg",
    landlocked: false,
  },
  {
    id: "056",
    name: "Belgium",
    capital: ["Brussels"],
    flag: "https://flagcdn.com/be.svg",
    landlocked: false,
  },
  {
    id: "583",
    name: "Micronesia",
    capital: ["Palikir"],
    flag: "https://flagcdn.com/fm.svg",
    landlocked: false,
  },
  {
    id: "226",
    name: "Equatorial Guinea",
    capital: ["Malabo"],
    flag: "https://flagcdn.com/gq.svg",
    landlocked: false,
  },
  {
    id: "833",
    name: "Isle of Man",
    capital: ["Douglas"],
    flag: "https://flagcdn.com/im.svg",
    landlocked: false,
  },
  {
    id: "188",
    name: "Costa Rica",
    capital: ["San José"],
    flag: "https://flagcdn.com/cr.svg",
    landlocked: false,
  },
  {
    id: "276",
    name: "Germany",
    capital: ["Berlin"],
    flag: "https://flagcdn.com/de.svg",
    landlocked: false,
  },
  {
    id: "478",
    name: "Mauritania",
    capital: ["Nouakchott"],
    flag: "https://flagcdn.com/mr.svg",
    landlocked: false,
  },
  {
    id: "756",
    name: "Switzerland",
    capital: ["Bern"],
    flag: "https://flagcdn.com/ch.svg",
    landlocked: true,
  },
  {
    id: "336",
    name: "Vatican City",
    capital: ["Vatican City"],
    flag: "https://flagcdn.com/va.svg",
    landlocked: true,
  },
  {
    id: "581",
    name: "United States Minor Outlying Islands",
    capital: "__vue_devtool_undefined__",
    flag: "https://flagcdn.com/um.svg",
    landlocked: false,
  },
  {
    id: "704",
    name: "Vietnam",
    capital: ["Hanoi"],
    flag: "https://flagcdn.com/vn.svg",
    landlocked: false,
  },
  {
    id: "728",
    name: "South Sudan",
    capital: ["Juba"],
    flag: "https://flagcdn.com/ss.svg",
    landlocked: true,
  },
  {
    id: "710",
    name: "South Africa",
    capital: ["Pretoria", "Bloemfontein", "Cape Town"],
    flag: "https://flagcdn.com/za.svg",
    landlocked: false,
  },
  {
    id: "180",
    name: "DR Congo",
    capital: ["Kinshasa"],
    flag: "https://flagcdn.com/cd.svg",
    landlocked: false,
  },
  {
    id: "780",
    name: "Trinidad and Tobago",
    capital: ["Port of Spain"],
    flag: "https://flagcdn.com/tt.svg",
    landlocked: false,
  },
  {
    id: "466",
    name: "Mali",
    capital: ["Bamako"],
    flag: "https://flagcdn.com/ml.svg",
    landlocked: true,
  },
  {
    id: "744",
    name: "Svalbard and Jan Mayen",
    capital: ["Longyearbyen"],
    flag: "https://flagcdn.com/sj.svg",
    landlocked: false,
  },
  {
    id: "012",
    name: "Algeria",
    capital: ["Algiers"],
    flag: "https://flagcdn.com/dz.svg",
    landlocked: false,
  },
  {
    id: "275",
    name: "Palestine",
    capital: ["Ramallah"],
    flag: "https://flagcdn.com/ps.svg",
    landlocked: false,
  },
  {
    id: "703",
    name: "Slovakia",
    capital: ["Bratislava"],
    flag: "https://flagcdn.com/sk.svg",
    landlocked: true,
  },
  {
    id: "508",
    name: "Mozambique",
    capital: ["Maputo"],
    flag: "https://flagcdn.com/mz.svg",
    landlocked: false,
  },
  {
    id: "032",
    name: "Argentina",
    capital: ["Buenos Aires"],
    flag: "https://flagcdn.com/ar.svg",
    landlocked: false,
  },
  {
    id: "203",
    name: "Czechia",
    capital: ["Prague"],
    flag: "https://flagcdn.com/cz.svg",
    landlocked: true,
  },
  {
    id: "242",
    name: "Fiji",
    capital: ["Suva"],
    flag: "https://flagcdn.com/fj.svg",
    landlocked: false,
  },
  {
    id: "016",
    name: "American Samoa",
    capital: ["Pago Pago"],
    flag: "https://flagcdn.com/as.svg",
    landlocked: false,
  },
  {
    id: "304",
    name: "Greenland",
    capital: ["Nuuk"],
    flag: "https://flagcdn.com/gl.svg",
    landlocked: false,
  },
  {
    id: "616",
    name: "Poland",
    capital: ["Warsaw"],
    flag: "https://flagcdn.com/pl.svg",
    landlocked: false,
  },
  {
    id: "086",
    name: "British Indian Ocean Territory",
    capital: ["Diego Garcia"],
    flag: "https://flagcdn.com/io.svg",
    landlocked: false,
  },
  {
    id: "548",
    name: "Vanuatu",
    capital: ["Port Vila"],
    flag: "https://flagcdn.com/vu.svg",
    landlocked: false,
  },
  {
    id: "760",
    name: "Syria",
    capital: ["Damascus"],
    flag: "https://flagcdn.com/sy.svg",
    landlocked: false,
  },
  {
    id: "010",
    name: "Antarctica",
    capital: "__vue_devtool_undefined__",
    flag: "https://flagcdn.com/aq.svg",
    landlocked: false,
  },
  {
    id: "740",
    name: "Suriname",
    capital: ["Paramaribo"],
    flag: "https://flagcdn.com/sr.svg",
    landlocked: false,
  },
  {
    id: "024",
    name: "Angola",
    capital: ["Luanda"],
    flag: "https://flagcdn.com/ao.svg",
    landlocked: false,
  },
  {
    id: "084",
    name: "Belize",
    capital: ["Belmopan"],
    flag: "https://flagcdn.com/bz.svg",
    landlocked: false,
  },
  {
    id: "308",
    name: "Grenada",
    capital: ["St. George's"],
    flag: "https://flagcdn.com/gd.svg",
    landlocked: false,
  },
  {
    id: "499",
    name: "Montenegro",
    capital: ["Podgorica"],
    flag: "https://flagcdn.com/me.svg",
    landlocked: false,
  },
  {
    id: "334",
    name: "Heard Island and McDonald Islands",
    capital: "__vue_devtool_undefined__",
    flag: "https://flagcdn.com/hm.svg",
    landlocked: false,
  },
  {
    id: "376",
    name: "Israel",
    capital: ["Jerusalem"],
    flag: "https://flagcdn.com/il.svg",
    landlocked: false,
  },
  {
    id: "624",
    name: "Guinea-Bissau",
    capital: ["Bissau"],
    flag: "https://flagcdn.com/gw.svg",
    landlocked: false,
  },
  {
    id: "558",
    name: "Nicaragua",
    capital: ["Managua"],
    flag: "https://flagcdn.com/ni.svg",
    landlocked: false,
  },
  {
    id: "446",
    name: "Macau",
    capital: "__vue_devtool_undefined__",
    flag: "https://flagcdn.com/mo.svg",
    landlocked: false,
  },
  {
    id: "608",
    name: "Philippines",
    capital: ["Manila"],
    flag: "https://flagcdn.com/ph.svg",
    landlocked: false,
  },
  {
    id: "384",
    name: "Ivory Coast",
    capital: ["Yamoussoukro"],
    flag: "https://flagcdn.com/ci.svg",
    landlocked: false,
  },
  {
    id: "158",
    name: "Taiwan",
    capital: ["Taipei"],
    flag: "https://flagcdn.com/tw.svg",
    landlocked: false,
  },
  {
    id: "646",
    name: "Rwanda",
    capital: ["Kigali"],
    flag: "https://flagcdn.com/rw.svg",
    landlocked: true,
  },
  {
    id: "663",
    name: "Saint Martin",
    capital: ["Marigot"],
    flag: "https://flagcdn.com/mf.svg",
    landlocked: false,
  },
  {
    id: "682",
    name: "Saudi Arabia",
    capital: ["Riyadh"],
    flag: "https://flagcdn.com/sa.svg",
    landlocked: false,
  },
  {
    id: "854",
    name: "Burkina Faso",
    capital: ["Ouagadougou"],
    flag: "https://flagcdn.com/bf.svg",
    landlocked: true,
  },
  {
    id: "562",
    name: "Niger",
    capital: ["Niamey"],
    flag: "https://flagcdn.com/ne.svg",
    landlocked: true,
  },
  {
    id: "591",
    name: "Panama",
    capital: ["Panama City"],
    flag: "https://flagcdn.com/pa.svg",
    landlocked: false,
  },
  {
    id: "535",
    name: "Caribbean Netherlands",
    capital: ["Kralendijk"],
    flag: "https://flagcdn.com/bq.svg",
    landlocked: false,
  },
  {
    id: "166",
    name: "Cocos (Keeling) Islands",
    capital: ["West Island"],
    flag: "https://flagcdn.com/cc.svg",
    landlocked: false,
  },
  {
    id: "410",
    name: "South Korea",
    capital: ["Seoul"],
    flag: "https://flagcdn.com/kr.svg",
    landlocked: false,
  },
  {
    id: "380",
    name: "Italy",
    capital: ["Rome"],
    flag: "https://flagcdn.com/it.svg",
    landlocked: false,
  },
  {
    id: "140",
    name: "Central African Republic",
    capital: ["Bangui"],
    flag: "https://flagcdn.com/cf.svg",
    landlocked: true,
  },
  {
    id: "654",
    name: "Saint Helena, Ascension and Tristan da Cunha",
    capital: ["Jamestown"],
    flag: "https://flagcdn.com/sh.svg",
    landlocked: false,
  },
  {
    id: "268",
    name: "Georgia",
    capital: ["Tbilisi"],
    flag: "https://flagcdn.com/ge.svg",
    landlocked: false,
  },
  {
    id: "170",
    name: "Colombia",
    capital: ["Bogotá"],
    flag: "https://flagcdn.com/co.svg",
    landlocked: false,
  },
  {
    id: "174",
    name: "Comoros",
    capital: ["Moroni"],
    flag: "https://flagcdn.com/km.svg",
    landlocked: false,
  },
  {
    id: "762",
    name: "Tajikistan",
    capital: ["Dushanbe"],
    flag: "https://flagcdn.com/tj.svg",
    landlocked: true,
  },
  {
    id: "136",
    name: "Cayman Islands",
    capital: ["George Town"],
    flag: "https://flagcdn.com/ky.svg",
    landlocked: false,
  },
  {
    id: "442",
    name: "Luxembourg",
    capital: ["Luxembourg"],
    flag: "https://flagcdn.com/lu.svg",
    landlocked: true,
  },
  {
    id: "296",
    name: "Kiribati",
    capital: ["South Tarawa"],
    flag: "https://flagcdn.com/ki.svg",
    landlocked: false,
  },
  {
    id: "020",
    name: "Andorra",
    capital: ["Andorra la Vella"],
    flag: "https://flagcdn.com/ad.svg",
    landlocked: true,
  },
  {
    id: "612",
    name: "Pitcairn Islands",
    capital: ["Adamstown"],
    flag: "https://flagcdn.com/pn.svg",
    landlocked: false,
  },
  {
    id: "643",
    name: "Russia",
    capital: ["Moscow"],
    flag: "https://flagcdn.com/ru.svg",
    landlocked: false,
  },
  {
    id: "388",
    name: "Jamaica",
    capital: ["Kingston"],
    flag: "https://flagcdn.com/jm.svg",
    landlocked: false,
  },
  {
    id: "192",
    name: "Cuba",
    capital: ["Havana"],
    flag: "https://flagcdn.com/cu.svg",
    landlocked: false,
  },
  {
    id: "686",
    name: "Senegal",
    capital: ["Dakar"],
    flag: "https://flagcdn.com/sn.svg",
    landlocked: false,
  },
  {
    id: "044",
    name: "Bahamas",
    capital: ["Nassau"],
    flag: "https://flagcdn.com/bs.svg",
    landlocked: false,
  },
  {
    id: "262",
    name: "Djibouti",
    capital: ["Djibouti"],
    flag: "https://flagcdn.com/dj.svg",
    landlocked: false,
  },
  {
    id: "076",
    name: "Brazil",
    capital: ["Brasília"],
    flag: "https://flagcdn.com/br.svg",
    landlocked: false,
  },
  {
    id: "729",
    name: "Sudan",
    capital: ["Khartoum"],
    flag: "https://flagcdn.com/sd.svg",
    landlocked: false,
  },
  {
    id: "788",
    name: "Tunisia",
    capital: ["Tunis"],
    flag: "https://flagcdn.com/tn.svg",
    landlocked: false,
  },
  {
    id: "196",
    name: "Cyprus",
    capital: ["Nicosia"],
    flag: "https://flagcdn.com/cy.svg",
    landlocked: false,
  },
  {
    id: "504",
    name: "Morocco",
    capital: ["Rabat"],
    flag: "https://flagcdn.com/ma.svg",
    landlocked: false,
  },
  {
    id: "660",
    name: "Anguilla",
    capital: ["The Valley"],
    flag: "https://flagcdn.com/ai.svg",
    landlocked: false,
  },
  {
    id: "784",
    name: "United Arab Emirates",
    capital: ["Abu Dhabi"],
    flag: "https://flagcdn.com/ae.svg",
    landlocked: false,
  },
  {
    id: "732",
    name: "Western Sahara",
    capital: ["El Aaiún"],
    flag: "https://flagcdn.com/eh.svg",
    landlocked: false,
  },
  {
    id: "516",
    name: "Namibia",
    capital: ["Windhoek"],
    flag: "https://flagcdn.com/na.svg",
    landlocked: false,
  },
  {
    id: "100",
    name: "Bulgaria",
    capital: ["Sofia"],
    flag: "https://flagcdn.com/bg.svg",
    landlocked: false,
  },
  {
    id: "404",
    name: "Kenya",
    capital: ["Nairobi"],
    flag: "https://flagcdn.com/ke.svg",
    landlocked: false,
  },
  {
    id: "748",
    name: "Eswatini",
    capital: ["Mbabane"],
    flag: "https://flagcdn.com/sz.svg",
    landlocked: true,
  },
  {
    id: "364",
    name: "Iran",
    capital: ["Tehran"],
    flag: "https://flagcdn.com/ir.svg",
    landlocked: false,
  },
  {
    id: "418",
    name: "Laos",
    capital: ["Vientiane"],
    flag: "https://flagcdn.com/la.svg",
    landlocked: true,
  },
  {
    id: "214",
    name: "Dominican Republic",
    capital: ["Santo Domingo"],
    flag: "https://flagcdn.com/do.svg",
    landlocked: false,
  },
  {
    id: "678",
    name: "São Tomé and Príncipe",
    capital: ["São Tomé"],
    flag: "https://flagcdn.com/st.svg",
    landlocked: false,
  },
  {
    id: "233",
    name: "Estonia",
    capital: ["Tallinn"],
    flag: "https://flagcdn.com/ee.svg",
    landlocked: false,
  },
  {
    id: "840",
    name: "United States",
    capital: ["Washington, D.C."],
    flag: "https://flagcdn.com/us.svg",
    landlocked: false,
  },
  {
    id: "004",
    name: "Afghanistan",
    capital: ["Kabul"],
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
    landlocked: true,
  },
  {
    id: "266",
    name: "Gabon",
    capital: ["Libreville"],
    flag: "https://flagcdn.com/ga.svg",
    landlocked: false,
  },
  {
    id: "258",
    name: "French Polynesia",
    capital: ["Papeetē"],
    flag: "https://flagcdn.com/pf.svg",
    landlocked: false,
  },
  {
    id: "414",
    name: "Kuwait",
    capital: ["Kuwait City"],
    flag: "https://flagcdn.com/kw.svg",
    landlocked: false,
  },
  {
    id: "598",
    name: "Papua New Guinea",
    capital: ["Port Moresby"],
    flag: "https://flagcdn.com/pg.svg",
    landlocked: false,
  },
  {
    id: "152",
    name: "Chile",
    capital: ["Santiago"],
    flag: "https://flagcdn.com/cl.svg",
    landlocked: false,
  },
  {
    id: "356",
    name: "India",
    capital: ["New Delhi"],
    flag: "https://flagcdn.com/in.svg",
    landlocked: false,
  },
  {
    id: "400",
    name: "Jordan",
    capital: ["Amman"],
    flag: "https://flagcdn.com/jo.svg",
    landlocked: false,
  },
  {
    id: "800",
    name: "Uganda",
    capital: ["Kampala"],
    flag: "https://flagcdn.com/ug.svg",
    landlocked: true,
  },
  {
    id: "008",
    name: "Albania",
    capital: ["Tirana"],
    flag: "https://flagcdn.com/al.svg",
    landlocked: false,
  },
  {
    id: "156",
    name: "China",
    capital: ["Beijing"],
    flag: "https://flagcdn.com/cn.svg",
    landlocked: false,
  },
  {
    id: "108",
    name: "Burundi",
    capital: ["Gitega"],
    flag: "https://flagcdn.com/bi.svg",
    landlocked: true,
  },
  {
    id: "031",
    name: "Azerbaijan",
    capital: ["Baku"],
    flag: "https://flagcdn.com/az.svg",
    landlocked: true,
  },
  {
    id: "048",
    name: "Bahrain",
    capital: ["Manama"],
    flag: "https://flagcdn.com/bh.svg",
    landlocked: false,
  },
  {
    id: "705",
    name: "Slovenia",
    capital: ["Ljubljana"],
    flag: "https://flagcdn.com/si.svg",
    landlocked: false,
  },
  {
    id: "894",
    name: "Zambia",
    capital: ["Lusaka"],
    flag: "https://flagcdn.com/zm.svg",
    landlocked: true,
  },
  {
    id: "724",
    name: "Spain",
    capital: ["Madrid"],
    flag: "https://flagcdn.com/es.svg",
    landlocked: false,
  },
  {
    id: "204",
    name: "Benin",
    capital: ["Porto-Novo"],
    flag: "https://flagcdn.com/bj.svg",
    landlocked: false,
  },
  {
    id: "132",
    name: "Cape Verde",
    capital: ["Praia"],
    flag: "https://flagcdn.com/cv.svg",
    landlocked: false,
  },
  {
    id: "096",
    name: "Brunei",
    capital: ["Bandar Seri Begawan"],
    flag: "https://flagcdn.com/bn.svg",
    landlocked: false,
  },
  {
    id: "584",
    name: "Marshall Islands",
    capital: ["Majuro"],
    flag: "https://flagcdn.com/mh.svg",
    landlocked: false,
  },
];
